name: package & push to marketplace

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: action-get-npm-version@master        
      id: version
    - run: |
        npm install
        npm install vsce
        npm run package
        echo 'CURRENT VERSION IS:  ${{ steps.version.outputs.version }}'
