name: package & push to marketplace

on:
  workflow_dispatch:


jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - uses: pchynoweth/action-get-npm-version@master
      id: version
    - run: |
        npm install
        npm install vsce
        npm run package
        echo 'CURRENT VERSION IS:  ${{ steps.version.outputs.version }}'
    
    - uses: actions/github-script@v5
      id: new_version
      with:
        script: |
          const vr = "${{ steps.version.outputs.version }}"
          const varr = vr.split(".");
          const newVersion = '' + varr[0] + '.' + varr[1] + '.' + (parseInt(varr[2])+1)         
          console.log('new VERSION', newVersion);
          return newVersion;
        result-encoding: string

    - run: |
        echo "newversion is"  ${{ steps.new_version.outputs.result }}
        sed -i -e 's/${{ steps.version.outputs.version }}/${{ steps.new_version.outputs.result }}/g' package.json
        sed -i -e 's/animations-${{ steps.version.outputs.version }}/animations-${{ steps.new_version.outputs.result }}/g' README.md
        echo "$(<package.json)"
        echo "$(<README.md)"
        
    - run: |
        git config user.email "ghostdev@gh.com"
        git config user.name "ghostdev"   
        git branch --show-current
        git add -A         
        git commit -m "auto increase version number"
        git status
        git push        
        

    
