name: package & push to marketplace

on:
  workflow_dispatch:


jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - uses: pchynoweth/action-get-npm-version@master
      id: version
    - run: |
        npm install
        npm install vsce
        npm run package
        echo 'CURRENT VERSION IS:  ${{ steps.version.outputs.version }}'
    
    - uses: actions/github-script@v5
      with:
        script: |
          const vr = "${{ steps.version.outputs.version }}"
          console.log(vr);
          console.log(vr.split("."))
